#!/usr/bin/env bash

SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
CONFIG_DIR="${XDG_CONFIG_HOME:-"$HOME/.config"}"
TMUX_CONFIG_DIR="$CONFIG_DIR/tmux"

mkdir -pv "$TMUX_CONFIG_DIR"
ln -sv "$SCRIPT_DIR/tmux.conf" "$TMUX_CONFIG_DIR"
